:icons: font
:source-highlighter: highlightjs
:sectnums:
:toc:

== Pruebas con Spring Boot
Ejemplo de creación de un API rest usando Spring boot

[IMPORTANT]
El proyecto está configurado para usar java 21

Vamos a ver cómo crear un API REST básico con Spring boot. Esta no es la manera habitual de hacerlo, es simplemente un un ejemplo para enteder los concepto básicos que se manejan.

Para este ejemplo usaremos la clase *Evento*, pensada para modelar un 'evento' social como por ejemplo esa cena entre amigos:

[source, java]
----
package org.rlnieto.tutoriales.apibasico.model;

import java.sql.Date;
import java.sql.Time;

public class Evento {
    private Long id;
    private String motivo;
    private short tipo;
    private Date fecha;
    private Time hora;

    public Evento(){}

    // Getters & setters
    public Long getId() {return id;}
    public String getMotivo() {return motivo;}
    public void setMotivo(String motivo) {this.motivo = motivo;}
    public short getTipo() {return tipo;}
    public void setTipo(short tipo) {this.tipo = tipo;}
    public Date getFecha() {return fecha;}
    public void setFecha(Date fecha) {this.fecha = fecha;}
    public Time getHora() {return hora;}
    public void setHora(Time hora) {this.hora = hora;}
}

----

== Enpoints
Crear un endpoint con Spring boot es muy simple, sólo tenemos que crear una clase de tipo *RestController* y anotar los métodos que 'atenderán' las urls de nuestra API. Vamos a definir las siguientes rutas:

* GET:
** Consulta de un evento indicando la clave en el path:
** Consulta de un evento indicando la clave en el body:
* POST:
** Alta de un evento indicando los datos en el body
* DELETE:
** Borrado de un evento indicando la clave en el body
* PUT:
** Actualización de un evento indicando la clave en el path y los datos en el body
* PATCH:
** Actualización de un evento indicando la clave en el path y los datos en el body. La diferencia con PUT es que en el primer caso se envían todos los datos de la entidad y con PATCH solamente los valores que cambian

De momento no tenemos una BD en la que guardar los eventos y vamos a usar una colección

Puedes ejecutar el proyecto ejecutando la clase *Application* desde el IDE que estés utilizando o con maven desde consola:
[source, bash]
----
mvn clean spring-boot:run
----

El proyecto está configurado para que se muestre una página de error cuando se solicita una url incorrecta. El código de esa página de error está en *resources/templates* (html) y *resources/static* (css). Estas páginas son renderizadas usando el motor de plantillas https://www.thymeleaf.org/[thymeleaf], para ello sólo hay que añadir la dependencia al pom:

[source, xml]
----
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-thymeleaf</artifactId>
</dependency>
----


=== GET básico con datos en el path

